Repository Logan1x/qwiklabs, pull requests merged in 2020-10, with the labels that each got.

#2 Changed the notebook issue to custom intent refresh
  labs/[11881]_building-interactice-apps-with-google-assistant-challenge-lab/guide.md
Labels: enhancement, hacktoberfest-accepted

#4 Enhanced the Readme.md with meaningful emojis!
  README.md
Labels: bug, enhancement, hacktoberfest-accepted

#5 function impleted for try except
  labs/[1740]_migrate_a_mysql_database_to_google_cloud_sql/quide.md
Labels: enhancement, hacktoberfest-accepted

#6 added contribution guideline
  CONTRIBUTING.md
Labels: hacktoberfest-accepted
